name: Flake8 Workflow

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python virtual environment
      uses: getsentry/action-setup-venv@v2.1.1
      id: venv
      with:
        python-version: '3.x'
        cache-dependency-path: |
          requirements.txt
          requirements-frozen.txt
        install-cmd: pip install -r requirements.txt

    - name: Flake8
      run: flake8 src/
